AMST4.Carousel.MVC/Controllers/SizeController.cs
using AMST4.Carousel.MVC.Data;
using AMST4.Carousel.MVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AMST4.Carousel.MVC.Controllers;

public class SizeController : Controller
{
    private readonly DataContext _context;

    public SizeController(DataContext context)
    {
        _context = context;
    }

    public async Task<IActionResult> SizeList()
    {
        return View(await _context.Size.ToListAsync());
    }

    public async Task<IActionResult> SizeDetails(Guid? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var size = await _context.Size
            .FirstOrDefaultAsync(m => m.Id == id);
        if (size == null)
        {
            return NotFound();
        }

        return View(size);
    }

    public IActionResult AddSize()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> AddSize(Size size)
    {

        size.Id = Guid.NewGuid();
        _context.Add(size);
        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(SizeList));

    }

    public async Task<IActionResult> EditSize(Guid? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var size = await _context.Size.FindAsync(id);
        if (size == null)
        {
            return NotFound();
        }
        return View(size);
    }

    [HttpPost]
    public async Task<IActionResult> EditSize(Guid id, Size size)
    {
        if (id != size.Id)
        {
            return NotFound();
        }

        _context.Update(size);
        await _context.SaveChangesAsync();

        return RedirectToAction(nameof(SizeList));

    }
    [HttpGet]

    public async Task<IActionResult> DeleteSize(Guid? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var size = await _context.Size
            .FirstOrDefaultAsync(m => m.Id == id);
        if (size == null)
        {
            return NotFound();
        }

        return View(size);
    }

    [HttpPost]
    public async Task<IActionResult> DeleteSizeConfirmed(Guid id)
    {
        var size = await _context.Size.FindAsync(id);
        if (size != null)
        {
            _context.Size.Remove(size);
        }

        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(SizeList));
    }

    [HttpPost]
    public async Task<IActionResult> DeleteSizeWarning(Guid id)
    {
        var size = await _context.Size.FindAsync(id);
        if (size == null)
        {
            return NotFound();
        }

        var hasProducts = await _context.Product.AnyAsync(p => p.Size_Id == size.Id);
        if (hasProducts)
        {
            ViewBag.HasProducts = true;
            ViewBag.SizeDescription = size.Description;
            return View("DeleteSizeWarning", size);
        }
        else
        {
            await DeleteSizeConfirmed(id);
        }

        return RedirectToAction("SizeList");
    }

    private bool SizeExists(Guid id)
    {
        return _context.Size.Any(e => e.Id == id);
    }
}

AMST4.Carousel.MVC/Controllers/UserController.cs
using AMST4.Carousel.MVC.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace AMST4.Carousel.MVC.Controllers;

public class UserController : Controller
{
    private readonly UserManager<User> _userManager;
    public readonly SignInManager<User> _signInManager;
    public UserController(UserManager<User> userManager, SignInManager<User> signInManager)
    {   
        _userManager = userManager;
        _signInManager = signInManager;

    }

    [HttpGet]
    public IActionResult AddUser()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> AddUser(User user)
    {
        var userExists = await IsEmailInUse(user.Email);
        if (userExists)
        {
            ViewBag.ErrorMessage = "Este email Já esta em Uso";
            return View(user);
        }
        var userNameExists = await IsUserNameInUse(user.UserName);
        if (!userNameExists)
        {
            ViewBag.ErrorMessage = "Este Nome de Usuário Já esta em Uso";
            return View(user);
        }

        user.Id = Guid.NewGuid().ToString();
        var result = await _userManager.CreateAsync(user, user.Password);

        if (result.Succeeded)
        {
            return RedirectToAction("ProductList", "Product");
        }

        ViewBag.ErrorMessage = "Aconteceu um Erro ao Tentar Criar sua Conta";
        return View(user);
    }


    [HttpGet]
    public IActionResult LoginUser()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> LoginUser(User user)
    {
        var UserExit = await IsEmailInUse(user.Email);
        if (UserExit)
        {
            var result = await _signInManager.PasswordSignInAsync(user.UserName, user.Password, false, false);
            if (result.Succeeded)
            {
                return RedirectToAction("ProductList", "Product");
            }
        } else
        {
            ViewBag.ErrorMessage = "Não encontramos uma conta associada a este endereço de e-mail";
            return View(user);
        }
        return RedirectToAction("LoginUser");
    }
 

    [HttpGet]
    public async Task<IActionResult> UserDetails(string id)
    {
        var user = await _userManager.FindByIdAsync(id);
        return View(user);
    }

    [HttpGet]
    public async Task<IActionResult> UserEdit(string id)
    {
        var user = await _userManager.FindByIdAsync(id);
        return View(user);
    }

    [HttpPost]
    public async Task<IActionResult> UserEdit(User user)
    {
        var userEdit = await _userManager.FindByIdAsync(user.Id);
        userEdit.Adress = user.Adress;
        userEdit.City = user.City;
        userEdit.State = user.State;
        await _userManager.UpdateAsync(userEdit);
        return RedirectToAction("UserList");
    }

    private async Task<bool> IsEmailInUse(string email)
    {
        var user = await _userManager.FindByEmailAsync(email);
        return user != null;
    }

    private async Task<bool> IsUserNameInUse(string userName)
    {
        var user = await _userManager.FindByNameAsync(userName);
        return user != null;
    }

}

AMST4.Carousel.MVC/Views/Shared/_Carousel.cshtml
<div class="container-fluid p-0">
    <div id="homeCarousel" class="carousel slide" data-bs-ride="carousel">
        <ol class="carousel-indicators">
            <li data-bs-target="#homeCarousel" data-bs-slide-to="0" class="active"></li>
            <li data-bs-target="#homeCarousel" data-bs-slide-to="1"></li>
            <li data-bs-target="#homeCarousel" data-bs-slide-to="2"></li>
        </ol>

        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="~/images/shoes1.jpg" class="d-block w-100" alt="Coleção de Verão">
                <div class="carousel-caption d-md-block">
                    <h5>Coleção de Verão</h5>
                    <p>Descubra os estilos mais quentes da temporada.</p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="~/images/shoes2.jpg" class="d-block w-100" alt="Estilo Atemporal">
                <div class="carousel-caption d-md-block">
                    <h5>Estilo Atemporal</h5>
                    <p>Clássicos modernos que nunca saem de moda.</p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="~/images/shoes3.jpg" class="d-block w-100" alt="Conforto Casual">
                <div class="carousel-caption d-md-block">
                    <h5>Conforto Casual</h5>
                    <p>Para o dia a dia com máximo conforto e estilo.</p>
                </div>
            </div>
        </div>

        <a class="carousel-control-prev" href="#homeCarousel" role="button" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Anterior</span>
        </a>
        <a class="carousel-control-next" href="#homeCarousel" role="button" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Próximo</span>
        </a>
    </div>
</div>

AMST4.Carousel.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AMST4.Carousel.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AMST4.Carousel.MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AMST4.Carousel.MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="CategoryList">Listar Categorias</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="ProductList">Listar Produtos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="AddUser">Listar User</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Size" asp-action="SizeList">Ver Tamanhos Disponiveis</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - AMST4.Carousel.MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>